### ISSUE TITLE
SASL issues

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1014]
- ~~numeric 908 `PLAIN,AUTHCOOKIE,EXTERNAL :are available SASL mechanisms` is ignored~~
  - ~~https://github.com/ProgVal/Limnoria/issues/1015~~
  - ~~https://github.com/ircv3/ircv3-specifications/issues/34~~
  - https://github.com/ircv3/ircv3-specifications/issues/34#issuecomment-75896013
- [ ] If ECDSA-256-CHALLENGEAUTH fails, PLAIN is attempted instead of EXTERNAL.
  - The order should be ECDSA, EXTERNAL, PLAIN.
  - `INFO 2015-01-19T06:18:46 supybot queertech: SASL ECDSA-NIST256P-CHALLENGE failed, trying PLAIN.`
    - However I am unable to see PLAIN authentication happening so maybe this is an error?
- [x] networks like OFTC cannot be connected to (fix: https://github.com/ProgVal/Limnoria/pull/1013)
- [x] any network that supports SASL cannot be connected to if services are down (https://github.com/ProgVal/Limnoria/issues/854).
- [ ] messages.log/stdout doesn't tell which mechanism fails/succeeds (https://github.com/ProgVal/Limnoria/issues/846)
- [x] EXTERNAL is not attempted unless both certfile and networks.network.sasl.username are set. https://github.com/ProgVal/Limnoria/issues/1052
